<header>
	<div class="sub-header">
		<div class="logo">
			<div>
				<img src="../public/img/logo.jpg">
			</div>
			<div>
				<h1>Transporte Escolar</h1>
				<h2>Sistema de controle</h2>
			</div>
		</div>
		<div class="user">
			<p><span>Logado:<?php echo mostrar_login()?> </span> <a onclick="janela_mensagem('Sair','conta','../../php/request.php?page=Sair')"><i class="material-icons">exit_to_app</i></a></p>
		</div>
	</div>
</header>

<?php include'card-alert.inc' ?>