<head>
	<title>Transporte Escolar</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" type="text/css" href="<?=base_url('/public/css/estilo.css')?>">
	 <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
	<script src="<?=base_url('/public/js/jquery-2.1.3.js')?>"></script>
	 <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	 <script src="<?=base_url('/public/js/alert.js')?>"></script>
	<link rel="icon" href="<?=base_url('/public/img/icone-2.png')?>" type="image/png">
	<script src="<?=base_url('/public/js/jspdf.min.js')?>"></script>
	<script src="<?=base_url('/public/js/jspdf.plugin.autotable.js')?>"></script>
	<script src="<?=base_url('/public/js/PDF.js')?>"></script>
</head>